// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
	icons "github.com/iota-uz/icons/phosphor"
)

func init() {
	registry.Register(registry.Entry{
		Slug:        "alert",
		Name:        "Alert",
		Description: "Alert informs users about important events.",
		Category:    "daisyui",
		Body:        alertBody,
	})
}

func alertBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Alert", `@daisyui.Alert(daisyui.AlertConfig{
	Message: "12 unread messages. Tap to see.",
	Class:   "w-full",
	Icon:    templ.Raw(...),
})`, daisyui.Alert(daisyui.AlertConfig{
			Message: "12 unread messages. Tap to see.",
			Class:   "w-full",
			Icon:    icons.Info(icons.Props{Size: "24", Class: "shrink-0"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Info color", `@daisyui.Alert(daisyui.AlertConfig{
	Message: "New software update available.",
	Color:   "info",
	Class:   "w-full",
	Icon:    templ.Raw(...),
})`, daisyui.Alert(daisyui.AlertConfig{
			Message: "New software update available.",
			Color:   "info",
			Class:   "w-full",
			Icon:    icons.Info(icons.Props{Size: "24", Class: "shrink-0"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Success color", `@daisyui.Alert(daisyui.AlertConfig{
	Message: "Your purchase has been confirmed!",
	Color:   "success",
	Class:   "w-full",
	Icon:    templ.Raw(...),
})`, daisyui.Alert(daisyui.AlertConfig{
			Message: "Your purchase has been confirmed!",
			Color:   "success",
			Class:   "w-full",
			Icon:    icons.CheckCircle(icons.Props{Size: "24", Class: "shrink-0"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Warning color", `@daisyui.Alert(daisyui.AlertConfig{
	Message: "Warning: Invalid email address!",
	Color:   "warning",
	Class:   "w-full",
	Icon:    templ.Raw(...),
})`, daisyui.Alert(daisyui.AlertConfig{
			Message: "Warning: Invalid email address!",
			Color:   "warning",
			Class:   "w-full",
			Icon:    icons.Warning(icons.Props{Size: "24", Class: "shrink-0"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Error color", `@daisyui.Alert(daisyui.AlertConfig{
	Message: "Error! Task failed successfully.",
	Color:   "error",
	Class:   "w-full",
	Icon:    templ.Raw(...),
})`, daisyui.Alert(daisyui.AlertConfig{
			Message: "Error! Task failed successfully.",
			Color:   "error",
			Class:   "w-full",
			Icon:    icons.XCircle(icons.Props{Size: "24", Class: "shrink-0"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Alert soft style", `<div class="flex flex-col gap-2">
	@daisyui.Alert(daisyui.AlertConfig{Message: "12 unread messages. Tap to see.", Color: "info", Style: "soft", Class: "w-full"})
	@daisyui.Alert(daisyui.AlertConfig{Message: "Your purchase has been confirmed!", Color: "success", Style: "soft", Class: "w-full"})
	// ... one per color
</div>`, alertDemoSoftRow()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Alert outline style", `<div class="flex flex-col gap-2">
	@daisyui.Alert(daisyui.AlertConfig{Message: "12 unread messages. Tap to see.", Color: "info", Style: "outline", Class: "w-full"})
	@daisyui.Alert(daisyui.AlertConfig{Message: "Your purchase has been confirmed!", Color: "success", Style: "outline", Class: "w-full"})
	// ... one per color
</div>`, alertDemoOutlineRow()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Alert dash style", `<div class="flex flex-col gap-2">
	@daisyui.Alert(daisyui.AlertConfig{Message: "12 unread messages. Tap to see.", Color: "info", Style: "dash", Class: "w-full"})
	@daisyui.Alert(daisyui.AlertConfig{Message: "Your purchase has been confirmed!", Color: "success", Style: "dash", Class: "w-full"})
	// ... one per color
</div>`, alertDemoDashRow()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Alert with buttons + responsive", `@daisyui.Alert(daisyui.AlertConfig{
	Message: "we use cookies for no reason.",
	Class:   "w-full alert-vertical sm:alert-horizontal",
	Icon:    templ.Raw(...),
	Actions: alertDemoActionButtons(),
})

templ alertDemoActionButtons() {
	<div>
		@daisyui.Button(daisyui.ButtonConfig{Label: "Deny", Size: "sm"})
		@daisyui.Button(daisyui.ButtonConfig{Label: "Accept", Size: "sm", Color: "primary"})
	</div>
}`, daisyui.Alert(daisyui.AlertConfig{
			Message: "we use cookies for no reason.",
			Class:   "w-full alert-vertical sm:alert-horizontal",
			Icon:    icons.Info(icons.Props{Size: "24", Class: "shrink-0"}),
			Actions: alertDemoActionButtons(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Alert with title and description", `@daisyui.Alert(daisyui.AlertConfig{
	Title:   "New message!",
	Desc:    "You have 1 unread message",
	Class:   "w-full alert-vertical sm:alert-horizontal",
	Icon:    templ.Raw(...),
	Actions: daisyui.Button(daisyui.ButtonConfig{Label: "See", Size: "sm"}),
})`, daisyui.Alert(daisyui.AlertConfig{
			Title:   "New message!",
			Desc:    "You have 1 unread message",
			Class:   "w-full alert-vertical sm:alert-horizontal",
			Icon:    icons.Info(icons.Props{Size: "24", Class: "shrink-0"}),
			Actions: daisyui.Button(daisyui.ButtonConfig{Label: "See", Size: "sm"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Alert with glass", `@daisyui.Alert(daisyui.AlertConfig{
	Message: "Glass: translucent, blurred surface.",
	Glass:   true,
	Class:   "w-full",
})`, gallery.GlassBackdrop(daisyui.Alert(daisyui.AlertConfig{
			Message: "Glass: translucent, blurred surface.",
			Glass:   true,
			Class:   "w-full",
		}))).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func alertDemoActionButtons() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Button(daisyui.ButtonConfig{Label: "Deny", Size: "sm"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Button(daisyui.ButtonConfig{Label: "Accept", Size: "sm", Color: "primary"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func alertDemoSoftRow() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"flex flex-col gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "12 unread messages. Tap to see.", Color: "info", Style: "soft", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Your purchase has been confirmed!", Color: "success", Style: "soft", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Warning: Invalid email address!", Color: "warning", Style: "soft", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Error! Task failed successfully.", Color: "error", Style: "soft", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func alertDemoOutlineRow() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"flex flex-col gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "12 unread messages. Tap to see.", Color: "info", Style: "outline", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Your purchase has been confirmed!", Color: "success", Style: "outline", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Warning: Invalid email address!", Color: "warning", Style: "outline", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Error! Task failed successfully.", Color: "error", Style: "outline", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func alertDemoDashRow() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"flex flex-col gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "12 unread messages. Tap to see.", Color: "info", Style: "dash", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Your purchase has been confirmed!", Color: "success", Style: "dash", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Warning: Invalid email address!", Color: "warning", Style: "dash", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Alert(daisyui.AlertConfig{Message: "Error! Task failed successfully.", Color: "error", Style: "dash", Class: "w-full"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
