// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

func selectBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Select", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick a color",
	Options: []daisyui.SelectOption{
		{Value: "Crimson"},
		{Value: "Amber"},
		{Value: "Velvet"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a color",
			Options: []daisyui.SelectOption{
				{Value: "Crimson"},
				{Value: "Amber"},
				{Value: "Velvet"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Ghost (no background)", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick a font",
	Style:       "ghost",
	Options: []daisyui.SelectOption{
		{Value: "Inter"},
		{Value: "Poppins"},
		{Value: "Raleway"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a font",
			Style:       "ghost",
			Options: []daisyui.SelectOption{
				{Value: "Inter"},
				{Value: "Poppins"},
				{Value: "Raleway"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("With fieldset and labels", `@daisyui.Fieldset(daisyui.FieldsetConfig{
	Legend: "Browsers",
	Class:  "w-xs",
}, selectFieldsetBody())

templ selectFieldsetBody() {
	@daisyui.Select(daisyui.SelectConfig{
		Placeholder: "Pick a Browser",
		Options: []daisyui.SelectOption{
			{Value: "Chrome"},
			{Value: "FireFox"},
			{Value: "Safari"},
		},
	})
	<span class="label">Optional</span>
}`, daisyui.Fieldset(daisyui.FieldsetConfig{
			Legend: "Browsers",
			Class:  "w-xs",
		}, selectFieldsetBody())).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Primary color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick a text editor",
	Color:       "primary",
	Options: []daisyui.SelectOption{
		{Value: "VScode"},
		{Value: "VScode fork"},
		{Value: "Another VScode fork"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a text editor",
			Color:       "primary",
			Options: []daisyui.SelectOption{
				{Value: "VScode"},
				{Value: "VScode fork"},
				{Value: "Another VScode fork"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Secondary color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick a language",
	Color:       "secondary",
	Options: []daisyui.SelectOption{
		{Value: "Zig"},
		{Value: "Go"},
		{Value: "Rust"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a language",
			Color:       "secondary",
			Options: []daisyui.SelectOption{
				{Value: "Zig"},
				{Value: "Go"},
				{Value: "Rust"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Accent color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Color scheme",
	Color:       "accent",
	Options: []daisyui.SelectOption{
		{Value: "Light mode"},
		{Value: "Dark mode"},
		{Value: "System"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Color scheme",
			Color:       "accent",
			Options: []daisyui.SelectOption{
				{Value: "Light mode"},
				{Value: "Dark mode"},
				{Value: "System"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Neutral color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Server location",
	Color:       "neutral",
	Options: []daisyui.SelectOption{
		{Value: "North America"},
		{Value: "EU west"},
		{Value: "South East Asia"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Server location",
			Color:       "neutral",
			Options: []daisyui.SelectOption{
				{Value: "North America"},
				{Value: "EU west"},
				{Value: "South East Asia"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Info color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick a Framework",
	Color:       "info",
	Options: []daisyui.SelectOption{
		{Value: "React"},
		{Value: "Vue"},
		{Value: "Angular"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a Framework",
			Color:       "info",
			Options: []daisyui.SelectOption{
				{Value: "React"},
				{Value: "Vue"},
				{Value: "Angular"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Success color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick a Runtime",
	Color:       "success",
	Options: []daisyui.SelectOption{
		{Value: "npm"},
		{Value: "Bun"},
		{Value: "yarn"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a Runtime",
			Color:       "success",
			Options: []daisyui.SelectOption{
				{Value: "npm"},
				{Value: "Bun"},
				{Value: "yarn"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Warning color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick an OS",
	Color:       "warning",
	Options: []daisyui.SelectOption{
		{Value: "Windows"},
		{Value: "MacOS"},
		{Value: "Linux"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick an OS",
			Color:       "warning",
			Options: []daisyui.SelectOption{
				{Value: "Windows"},
				{Value: "MacOS"},
				{Value: "Linux"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Error color", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick an AI Model",
	Color:       "error",
	Options: []daisyui.SelectOption{
		{Value: "GPT-4"},
		{Value: "Claude"},
		{Value: "Llama"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick an AI Model",
			Color:       "error",
			Options: []daisyui.SelectOption{
				{Value: "GPT-4"},
				{Value: "Claude"},
				{Value: "Llama"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Sizes", `<div class="flex flex-col gap-4 w-full items-center">
	@daisyui.Select(daisyui.SelectConfig{Placeholder: "Xsmall", Size: "xs", Options: []daisyui.SelectOption{{Value: "Xsmall Apple"}}})
	@daisyui.Select(daisyui.SelectConfig{Placeholder: "Small", Size: "sm", Options: []daisyui.SelectOption{{Value: "Small Apple"}}})
	// ... one per size (md, lg, xl)
</div>`, selectSizeRow()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Disabled", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "You can't touch this",
	Disabled:    true,
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "You can't touch this",
			Disabled:    true,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Using OS native style for the options dropdown", `@daisyui.Select(daisyui.SelectConfig{
	Placeholder: "Pick a color",
	Class:       "appearance-none",
	Options: []daisyui.SelectOption{
		{Value: "Crimson"},
		{Value: "Amber"},
		{Value: "Velvet"},
	},
})`, daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a color",
			Class:       "appearance-none",
			Options: []daisyui.SelectOption{
				{Value: "Crimson"},
				{Value: "Amber"},
				{Value: "Velvet"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func selectFieldsetBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = daisyui.Select(daisyui.SelectConfig{
			Placeholder: "Pick a Browser",
			Options: []daisyui.SelectOption{
				{Value: "Chrome"},
				{Value: "FireFox"},
				{Value: "Safari"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"label\">Optional</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func selectSizeRow() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex flex-col gap-4 w-full items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Select(daisyui.SelectConfig{Placeholder: "Xsmall", Size: "xs", Options: []daisyui.SelectOption{{Value: "Xsmall Apple"}}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Select(daisyui.SelectConfig{Placeholder: "Small", Size: "sm", Options: []daisyui.SelectOption{{Value: "Small Apple"}}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Select(daisyui.SelectConfig{Placeholder: "Medium", Size: "md", Options: []daisyui.SelectOption{{Value: "Medium Apple"}}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Select(daisyui.SelectConfig{Placeholder: "Large", Size: "lg", Options: []daisyui.SelectOption{{Value: "Large Apple"}}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Select(daisyui.SelectConfig{Placeholder: "Xlarge", Size: "xl", Options: []daisyui.SelectOption{{Value: "Xlarge Apple"}}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func init() {
	registry.Register(registry.Entry{
		Slug:        "select",
		Name:        "Select",
		Description: "Select is used to pick a value from a list of options.",
		Category:    "daisyui",
		Body:        selectBody,
	})
}

var _ = templruntime.GeneratedTemplate
