// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

func tooltipBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Tooltip", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip:      "hello",
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Hover me"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip:      "hello",
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Hover me"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Tooltip with tooltip-content", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Content:  templ.Raw(...),
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Hover me"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Content:  templ.Raw(`<div class="animate-bounce text-orange-400 -rotate-10 text-2xl font-black">Wow!</div>`),
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Hover me"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Force open", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip:      "hello",
	Open:     true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Force open"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip:      "hello",
			Open:     true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Force open"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Top", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "top", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Top"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "top", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Top"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Bottom", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "bottom", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Bottom"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "bottom", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Bottom"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Left", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "left", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Left"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "left", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Left"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Right", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "right", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Right"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "right", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Right"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Primary color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "primary", Color: "primary", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "primary", Color: "primary"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "primary", Color: "primary", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "primary", Color: "primary"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Secondary color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "secondary", Color: "secondary", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "secondary", Color: "secondary"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "secondary", Color: "secondary", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "secondary", Color: "secondary"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Accent color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "accent", Color: "accent", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "accent", Color: "accent"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "accent", Color: "accent", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "accent", Color: "accent"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Info color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "info", Color: "info", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "info", Color: "info"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "info", Color: "info", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "info", Color: "info"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Success color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "success", Color: "success", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "success", Color: "success"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "success", Color: "success", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "success", Color: "success"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Warning color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "warning", Color: "warning", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "warning", Color: "warning"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "warning", Color: "warning", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "warning", Color: "warning"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Error color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "error", Color: "error", Open: true,
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "error", Color: "error"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "error", Color: "error", Open: true,
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "error", Color: "error"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Responsive tooltip. only show for large screen", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip:      "hello",
	Class:    "lg:tooltip",
	Children: daisyui.Button(daisyui.ButtonConfig{Label: "Hover me"}),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip:      "hello",
			Class:    "lg:tooltip",
			Children: daisyui.Button(daisyui.ButtonConfig{Label: "Hover me"}),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func init() {
	registry.Register(registry.Entry{
		Slug:        "tooltip",
		Name:        "Tooltip",
		Description: "Tooltip can be used to show a message when hovering over an element.",
		Category:    "daisyui",
		Body:        tooltipBody,
	})
}

var _ = templruntime.GeneratedTemplate
