// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

func collapseBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Collapse with focus", `@daisyui.Collapse(
	daisyui.CollapseConfig{Class: "bg-base-100 border border-base-300"},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Class: "bg-base-100 border border-base-300"},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Collapse with checkbox", `@daisyui.Collapse(
	daisyui.CollapseConfig{Mode: "checkbox", Class: "bg-base-100 border border-base-300"},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Mode: "checkbox", Class: "bg-base-100 border border-base-300"},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Collapse using details and summary tag", `@daisyui.Collapse(
	daisyui.CollapseConfig{Mode: "details", Class: "bg-base-100 border border-base-300"},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Mode: "details", Class: "bg-base-100 border border-base-300"},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Without border and background color", `@daisyui.Collapse(
	daisyui.CollapseConfig{},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("With arrow icon", `@daisyui.Collapse(
	daisyui.CollapseConfig{Icon: "arrow", Class: "bg-base-100 border border-base-300"},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Icon: "arrow", Class: "bg-base-100 border border-base-300"},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("With arrow plus/minus icon", `@daisyui.Collapse(
	daisyui.CollapseConfig{Icon: "plus", Class: "bg-base-100 border border-base-300"},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Icon: "plus", Class: "bg-base-100 border border-base-300"},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Force open", `@daisyui.Collapse(
	daisyui.CollapseConfig{Open: true, Class: "bg-base-100 border border-base-300"},
	"I have collapse-open class",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Open: true, Class: "bg-base-100 border border-base-300"},
			"I have collapse-open class",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Force close", `@daisyui.Collapse(
	daisyui.CollapseConfig{Close: true, Class: "bg-base-100 border border-base-300"},
	"I have collapse-close class",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Close: true, Class: "bg-base-100 border border-base-300"},
			"I have collapse-close class",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Custom colors for collapse that works with focus", `@daisyui.Collapse(
	daisyui.CollapseConfig{Class: "bg-primary text-primary-content focus:bg-secondary focus:text-secondary-content"},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, daisyui.Collapse(
			daisyui.CollapseConfig{Class: "bg-primary text-primary-content focus:bg-secondary focus:text-secondary-content"},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Collapse with glass", `@daisyui.Collapse(
	daisyui.CollapseConfig{Glass: true, Icon: "arrow"},
	"How do I create an account?",
	"Click the \"Sign Up\" button in the top right corner and follow the registration process.",
)`, gallery.GlassBackdrop(daisyui.Collapse(
			daisyui.CollapseConfig{Glass: true, Icon: "arrow"},
			"How do I create an account?",
			`Click the "Sign Up" button in the top right corner and follow the registration process.`,
		))).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func init() {
	registry.Register(registry.Entry{
		Slug:        "collapse",
		Name:        "Collapse",
		Description: "Collapse is used for showing and hiding content.",
		Category:    "daisyui",
		Body:        collapseBody,
	})
}

var _ = templruntime.GeneratedTemplate
