// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"strconv"

	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

func tableBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Table", `@daisyui.Table(daisyui.TableConfig{
	Headers: []daisyui.TableCell{
		{Text: ""},
		{Text: "Name"},
		{Text: "Job"},
		{Text: "Favorite Color"},
	},
	Rows: []daisyui.TableRow{
		{
			Cells: []daisyui.TableCell{
				{Text: "1", Header: true},
				{Text: "Cy Ganderton"},
				{Text: "Quality Control Specialist"},
				{Text: "Blue"},
			},
		},
		// ... one row per person
	},
})`, daisyui.Table(daisyui.TableConfig{
			Headers: []daisyui.TableCell{
				{Text: ""},
				{Text: "Name"},
				{Text: "Job"},
				{Text: "Favorite Color"},
			},
			Rows: []daisyui.TableRow{
				{
					Cells: []daisyui.TableCell{
						{Text: "1", Header: true},
						{Text: "Cy Ganderton"},
						{Text: "Quality Control Specialist"},
						{Text: "Blue"},
					},
				},
				{
					Cells: []daisyui.TableCell{
						{Text: "2", Header: true},
						{Text: "Hart Hagerty"},
						{Text: "Desktop Support Technician"},
						{Text: "Purple"},
					},
				},
				{
					Cells: []daisyui.TableCell{
						{Text: "3", Header: true},
						{Text: "Brice Swyre"},
						{Text: "Tax Accountant"},
						{Text: "Red"},
					},
				},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table with border and background", `@daisyui.Table(daisyui.TableConfig{
	Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
	Rows: []daisyui.TableRow{
		{Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
		// ... one row per person
	},
	Class: "rounded-box border border-base-content/5 bg-base-100",
})`, daisyui.Table(daisyui.TableConfig{
			Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
			Rows: []daisyui.TableRow{
				{Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
				{Cells: []daisyui.TableCell{{Text: "2", Header: true}, {Text: "Hart Hagerty"}, {Text: "Desktop Support Technician"}, {Text: "Purple"}}},
				{Cells: []daisyui.TableCell{{Text: "3", Header: true}, {Text: "Brice Swyre"}, {Text: "Tax Accountant"}, {Text: "Red"}}},
			},
			Class: "rounded-box border border-base-content/5 bg-base-100",
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table with an active row", `@daisyui.Table(daisyui.TableConfig{
	Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
	Rows: []daisyui.TableRow{
		{Class: "bg-base-200", Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
		// ... one row per person
	},
})`, daisyui.Table(daisyui.TableConfig{
			Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
			Rows: []daisyui.TableRow{
				{Class: "bg-base-200", Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
				{Cells: []daisyui.TableCell{{Text: "2", Header: true}, {Text: "Hart Hagerty"}, {Text: "Desktop Support Technician"}, {Text: "Purple"}}},
				{Cells: []daisyui.TableCell{{Text: "3", Header: true}, {Text: "Brice Swyre"}, {Text: "Tax Accountant"}, {Text: "Red"}}},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table with a row that highlights on hover", `@daisyui.Table(daisyui.TableConfig{
	Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
	Rows: []daisyui.TableRow{
		{Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
		{Class: "hover:bg-base-300", Cells: []daisyui.TableCell{{Text: "2", Header: true}, {Text: "Hart Hagerty"}, {Text: "Desktop Support Technician"}, {Text: "Purple"}}},
		// ... more rows
	},
})`, daisyui.Table(daisyui.TableConfig{
			Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
			Rows: []daisyui.TableRow{
				{Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
				{Class: "hover:bg-base-300", Cells: []daisyui.TableCell{{Text: "2", Header: true}, {Text: "Hart Hagerty"}, {Text: "Desktop Support Technician"}, {Text: "Purple"}}},
				{Cells: []daisyui.TableCell{{Text: "3", Header: true}, {Text: "Brice Swyre"}, {Text: "Tax Accountant"}, {Text: "Red"}}},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Zebra", `@daisyui.Table(daisyui.TableConfig{
	Modifier: "zebra",
	Headers:  []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
	Rows: []daisyui.TableRow{
		{Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
		// ... one row per person
	},
})`, daisyui.Table(daisyui.TableConfig{
			Modifier: "zebra",
			Headers:  []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}},
			Rows: []daisyui.TableRow{
				{Cells: []daisyui.TableCell{{Text: "1", Header: true}, {Text: "Cy Ganderton"}, {Text: "Quality Control Specialist"}, {Text: "Blue"}}},
				{Cells: []daisyui.TableCell{{Text: "2", Header: true}, {Text: "Hart Hagerty"}, {Text: "Desktop Support Technician"}, {Text: "Purple"}}},
				{Cells: []daisyui.TableCell{{Text: "3", Header: true}, {Text: "Brice Swyre"}, {Text: "Tax Accountant"}, {Text: "Red"}}},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table with visual elements", `@daisyui.Table(daisyui.TableConfig{
	Headers: []daisyui.TableCell{
		{HTML: tableCheckboxCell()},
		{Text: "Name"},
		{Text: "Job"},
		{Text: "Favorite Color"},
		{Text: ""},
	},
	Rows: []daisyui.TableRow{
		{Cells: []daisyui.TableCell{
			{HTML: tableCheckboxCell()},
			{HTML: tableAvatarNameCell("Hart Hagerty", "United States", "https://...2@94.webp")},
			{HTML: tableJobCell("Zemlak, Daniel and Leannon", "Desktop Support Technician")},
			{Text: "Purple"},
			{HTML: tableDetailsButtonCell()},
		}},
		// ... one row per person
	},
	Footers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}, {Text: ""}},
})`, tableVisual()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table xs", `@daisyui.Table(daisyui.TableConfig{
	Size:    "xs",
	Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}},
	Rows:    tableXsRows(),
	Footers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}},
})`, daisyui.Table(daisyui.TableConfig{
			Size:    "xs",
			Headers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}},
			Rows:    tableXsRows(),
			Footers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table with pinned-rows", `@daisyui.Table(daisyui.TableConfig{
	Modifier:  "pin-rows",
	Class:     "bg-base-200",
	Wrap:      true,
	WrapClass: "h-96",
	Rows:      tablePinnedRows(),
})`, daisyui.Table(daisyui.TableConfig{
			Modifier:  "pin-rows",
			Class:     "bg-base-200",
			Wrap:      true,
			WrapClass: "h-96",
			Rows:      tablePinnedRows(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table with pinned-rows and pinned-cols", `@daisyui.Table(daisyui.TableConfig{
	Size:      "xs",
	Modifier:  "pin-rows",
	Class:     "table-pin-cols",
	Wrap:      true,
	WrapClass: "h-96 w-96",
	Headers:   []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}, {Text: ""}},
	Rows:      tablePinnedColsRows(),
	Footers:   []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}, {Text: ""}},
})`, daisyui.Table(daisyui.TableConfig{
			Size:      "xs",
			Modifier:  "pin-rows",
			Class:     "table-pin-cols",
			Wrap:      true,
			WrapClass: "h-96 w-96",
			Headers:   []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}, {Text: ""}},
			Rows:      tablePinnedColsRows(),
			Footers:   []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "company"}, {Text: "location"}, {Text: "Last Login"}, {Text: "Favorite Color"}, {Text: ""}},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Table with glass", `@daisyui.Table(daisyui.TableConfig{
	Glass: true,
	Headers: []daisyui.TableCell{
		{Text: ""},
		{Text: "Name"},
		{Text: "Job"},
		{Text: "Favorite Color"},
	},
	Rows: []daisyui.TableRow{
		{
			Cells: []daisyui.TableCell{
				{Text: "1", Header: true},
				{Text: "Cy Ganderton"},
				{Text: "Quality Control Specialist"},
				{Text: "Blue"},
			},
		},
		// ... one row per person
	},
})`, gallery.GlassBackdrop(daisyui.Table(daisyui.TableConfig{
			Glass: true,
			Headers: []daisyui.TableCell{
				{Text: ""},
				{Text: "Name"},
				{Text: "Job"},
				{Text: "Favorite Color"},
			},
			Rows: []daisyui.TableRow{
				{
					Cells: []daisyui.TableCell{
						{Text: "1", Header: true},
						{Text: "Cy Ganderton"},
						{Text: "Quality Control Specialist"},
						{Text: "Blue"},
					},
				},
				{
					Cells: []daisyui.TableCell{
						{Text: "2", Header: true},
						{Text: "Hart Hagerty"},
						{Text: "Desktop Support Technician"},
						{Text: "Purple"},
					},
				},
				{
					Cells: []daisyui.TableCell{
						{Text: "3", Header: true},
						{Text: "Brice Swyre"},
						{Text: "Tax Accountant"},
						{Text: "Red"},
					},
				},
			},
		}))).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tableVisual() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = daisyui.Table(daisyui.TableConfig{
			Headers: []daisyui.TableCell{
				{HTML: tableCheckboxCell()},
				{Text: "Name"},
				{Text: "Job"},
				{Text: "Favorite Color"},
				{Text: ""},
			},
			Rows: []daisyui.TableRow{
				{Cells: []daisyui.TableCell{
					{HTML: tableCheckboxCell()},
					{HTML: tableAvatarNameCell("Hart Hagerty", "United States", "https://img.daisyui.com/images/profile/demo/2@94.webp")},
					{HTML: tableJobCell("Zemlak, Daniel and Leannon", "Desktop Support Technician")},
					{Text: "Purple"},
					{HTML: tableDetailsButtonCell()},
				}},
				{Cells: []daisyui.TableCell{
					{HTML: tableCheckboxCell()},
					{HTML: tableAvatarNameCell("Brice Swyre", "China", "https://img.daisyui.com/images/profile/demo/3@94.webp")},
					{HTML: tableJobCell("Carroll Group", "Tax Accountant")},
					{Text: "Red"},
					{HTML: tableDetailsButtonCell()},
				}},
				{Cells: []daisyui.TableCell{
					{HTML: tableCheckboxCell()},
					{HTML: tableAvatarNameCell("Marjy Ferencz", "Russia", "https://img.daisyui.com/images/profile/demo/4@94.webp")},
					{HTML: tableJobCell("Rowe-Schoen", "Office Assistant I")},
					{Text: "Crimson"},
					{HTML: tableDetailsButtonCell()},
				}},
				{Cells: []daisyui.TableCell{
					{HTML: tableCheckboxCell()},
					{HTML: tableAvatarNameCell("Yancy Tear", "Brazil", "https://img.daisyui.com/images/profile/demo/5@94.webp")},
					{HTML: tableJobCell("Wyman-Ledner", "Community Outreach Specialist")},
					{Text: "Indigo"},
					{HTML: tableDetailsButtonCell()},
				}},
			},
			Footers: []daisyui.TableCell{{Text: ""}, {Text: "Name"}, {Text: "Job"}, {Text: "Favorite Color"}, {Text: ""}},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tableCheckboxCell() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<label><input type=\"checkbox\" class=\"checkbox\"></label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tableAvatarNameCell(name, country, src string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex items-center gap-3\"><div class=\"avatar\"><div class=\"w-12 h-12 mask mask-squircle\"><img src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.SafeURL(src))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_table.templ`, Line: 295, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" alt=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_table.templ`, Line: 295, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"></div></div><div><div class=\"font-bold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_table.templ`, Line: 299, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"text-sm opacity-50\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(country)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_table.templ`, Line: 300, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tableJobCell(company, role string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(company)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_table.templ`, Line: 306, Col: 10}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<br><span class=\"badge badge-ghost badge-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(role)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_table.templ`, Line: 308, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tableDetailsButtonCell() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var12 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var12 == nil {
			templ_7745c5c3_Var12 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<button class=\"btn btn-ghost btn-xs\">details</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tableXsRows() []daisyui.TableRow {
	data := []struct {
		idx                                        int
		name, job, company, location, login, color string
	}{
		{1, "Cy Ganderton", "Quality Control Specialist", "Littel, Schaden and Vandervort", "Canada", "12/16/2020", "Blue"},
		{2, "Hart Hagerty", "Desktop Support Technician", "Zemlak, Daniel and Leannon", "United States", "12/5/2020", "Purple"},
		{3, "Brice Swyre", "Tax Accountant", "Carroll Group", "China", "8/15/2020", "Red"},
		{4, "Marjy Ferencz", "Office Assistant I", "Rowe-Schoen", "Russia", "3/25/2021", "Crimson"},
		{5, "Yancy Tear", "Community Outreach Specialist", "Wyman-Ledner", "Brazil", "5/22/2020", "Indigo"},
		{6, "Irma Vasilik", "Editor", "Wiza, Bins and Emard", "Venezuela", "12/8/2020", "Purple"},
		{7, "Meghann Durtnal", "Staff Accountant IV", "Schuster-Schimmel", "Philippines", "2/17/2021", "Yellow"},
		{8, "Sammy Seston", "Accountant I", "O'Hara, Welch and Keebler", "Indonesia", "5/23/2020", "Crimson"},
		{9, "Lesya Tinham", "Safety Technician IV", "Turner-Kuhlman", "Philippines", "2/21/2021", "Maroon"},
		{10, "Zaneta Tewkesbury", "VP Marketing", "Sauer LLC", "Chad", "6/23/2020", "Green"},
		{11, "Andy Tipple", "Librarian", "Hilpert Group", "Poland", "7/9/2020", "Indigo"},
		{12, "Sophi Biles", "Recruiting Manager", "Gutmann Inc", "Indonesia", "2/12/2021", "Maroon"},
		{13, "Florida Garces", "Web Developer IV", "Gaylord, Pacocha and Baumbach", "Poland", "5/31/2020", "Purple"},
		{14, "Maribeth Popping", "Analyst Programmer", "Deckow-Pouros", "Portugal", "4/27/2021", "Aquamarine"},
		{15, "Moritz Dryburgh", "Dental Hygienist", "Schiller, Cole and Hackett", "Sri Lanka", "8/8/2020", "Crimson"},
		{16, "Reid Semiras", "Teacher", "Sporer, Sipes and Rogahn", "Poland", "7/30/2020", "Green"},
		{17, "Alec Lethby", "Teacher", "Reichel, Glover and Hamill", "China", "2/28/2021", "Khaki"},
		{18, "Aland Wilber", "Quality Control Specialist", "Kshlerin, Rogahn and Swaniawski", "Czech Republic", "9/29/2020", "Purple"},
		{19, "Teddie Duerden", "Staff Accountant III", "Pouros, Ullrich and Windler", "France", "10/27/2020", "Aquamarine"},
		{20, "Lorelei Blackstone", "Data Coordinator", "Witting, Kutch and Greenfelder", "Kazakhstan", "6/3/2020", "Red"},
	}
	rows := make([]daisyui.TableRow, len(data))
	for i, d := range data {
		rows[i] = daisyui.TableRow{Cells: []daisyui.TableCell{
			{Text: strconv.Itoa(d.idx), Header: true},
			{Text: d.name},
			{Text: d.job},
			{Text: d.company},
			{Text: d.location},
			{Text: d.login},
			{Text: d.color},
		}}
	}
	return rows
}

func tablePinnedRows() []daisyui.TableRow {
	letterRows := map[string][]string{
		"A": {"Ant-Man", "Aquaman", "Asterix", "The Atom", "The Avengers"},
		"B": {"Batgirl", "Batman", "Batwoman", "Black Canary", "Black Panther"},
		"C": {"Captain America", "Captain Marvel", "Catwoman", "Conan the Barbarian"},
		"D": {"Daredevil", "The Defenders", "Doc Savage", "Doctor Strange"},
		"E": {"Elektra"},
		"F": {"Fantastic Four"},
		"G": {"Ghost Rider", "Green Arrow", "Green Lantern", "Guardians of the Galaxy"},
		"H": {"Hawkeye", "Hellboy", "Incredible Hulk"},
		"I": {"Iron Fist", "Iron Man"},
		"M": {"Marvelman"},
		"R": {"Robin", "The Rocketeer"},
		"S": {"The Shadow", "Spider-Man", "Sub-Mariner", "Supergirl", "Superman"},
		"T": {"Teenage Mutant Ninja Turtles", "Thor"},
		"W": {"The Wasp", "Watchmen", "Wolverine", "Wonder Woman"},
		"X": {"X-Men"},
		"Z": {"Zatanna", "Zatara"},
	}
	letters := []string{"A", "B", "C", "D", "E", "F", "G", "H", "I", "M", "R", "S", "T", "W", "X", "Z"}
	rows := make([]daisyui.TableRow, 0, len(letters)*6)
	for _, l := range letters {
		names, ok := letterRows[l]
		if !ok {
			continue
		}
		rows = append(rows, daisyui.TableRow{Cells: []daisyui.TableCell{{Text: l, Header: true}}})
		for _, n := range names {
			rows = append(rows, daisyui.TableRow{Cells: []daisyui.TableCell{{Text: n}}})
		}
	}
	return rows
}

func tablePinnedColsRows() []daisyui.TableRow {
	xs := tableXsRows()
	rows := make([]daisyui.TableRow, len(xs))
	for i, r := range xs {
		cells := append([]daisyui.TableCell{{Text: r.Cells[0].Text, Header: true}}, r.Cells[1:]...)
		cells = append(cells, daisyui.TableCell{Text: r.Cells[0].Text, Header: true})
		rows[i] = daisyui.TableRow{Cells: cells}
	}
	return rows
}

func init() {
	registry.Register(registry.Entry{
		Slug:        "table",
		Name:        "Table",
		Description: "Table can be used to show a list of data in a table format.",
		Category:    "daisyui",
		Body:        tableBody,
	})
}

var _ = templruntime.GeneratedTemplate
