// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

const timelineCheckPath = `M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z`

func timelineCheckIcon() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\" class=\"h-5 w-5\"><path fill-rule=\"evenodd\" d=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(timelineCheckPath)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 13, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" clip-rule=\"evenodd\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func timelineCheckIconPrimary() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\" class=\"h-5 w-5 text-primary\"><path fill-rule=\"evenodd\" d=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(timelineCheckPath)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 19, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" clip-rule=\"evenodd\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func timelineBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Timeline with text on both sides and icon", `@daisyui.Timeline(daisyui.TimelineConfig{
	Items: timelineBothSidesItems(),
})

// timelineBothSidesItems returns []daisyui.TimelineItem:
{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("1984"), Box: false, HRAfter: true}
{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("1998"), HRBefore: true, HRAfter: true}
// ... one per year`, daisyui.Timeline(daisyui.TimelineConfig{
			Items: timelineBothSidesItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Timeline with bottom side only", `@daisyui.Timeline(daisyui.TimelineConfig{
	Items: timelineBottomOnlyItems(),
})

// timelineBottomOnlyItems returns one item per event, all on the end side:
{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true}
// ... one per event`, daisyui.Timeline(daisyui.TimelineConfig{
			Items: timelineBottomOnlyItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Timeline with top side only", `@daisyui.Timeline(daisyui.TimelineConfig{
	Items: timelineTopOnlyItems(),
})

// timelineTopOnlyItems returns one item per event, all on the start side:
{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true}
// ... one per event`, daisyui.Timeline(daisyui.TimelineConfig{
			Items: timelineTopOnlyItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Timeline with different sides", `@daisyui.Timeline(daisyui.TimelineConfig{
	Items: timelineDifferentSidesItems(),
})

// timelineDifferentSidesItems alternates start/end:
{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true}
{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineRaw("iMac"), Box: true, HRBefore: true, HRAfter: true}
// ... alternating sides`, daisyui.Timeline(daisyui.TimelineConfig{
			Items: timelineDifferentSidesItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Timeline with colorful lines", `@daisyui.Timeline(daisyui.TimelineConfig{
	Items: timelineColorfulItems(),
})

// timelineColorfulItems uses HRClass to color the connecting lines:
{Side: daisyui.TimelineSideStart, Icon: timelineCheckIconPrimary(), Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true, HRClass: "bg-primary"}
// ... HRClass: "bg-primary" on colored segments`, daisyui.Timeline(daisyui.TimelineConfig{
			Items: timelineColorfulItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Timeline without icons", `@daisyui.Timeline(daisyui.TimelineConfig{
	Items: timelineNoIconsItems(),
})

// timelineNoIconsItems omits the Icon field:
{Side: daisyui.TimelineSideStart, Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true}
// ... one per event, no Icon`, daisyui.Timeline(daisyui.TimelineConfig{
			Items: timelineNoIconsItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Vertical timeline with text on both sides and icon", `@daisyui.Timeline(daisyui.TimelineConfig{
	Direction: "vertical",
	Items:     timelineBothSidesItems(),
})`, daisyui.Timeline(daisyui.TimelineConfig{
			Direction: "vertical",
			Items:     timelineBothSidesItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Vertical timeline with right side only", `@daisyui.Timeline(daisyui.TimelineConfig{
	Direction: "vertical",
	Items:     timelineBottomOnlyItems(),
})`, daisyui.Timeline(daisyui.TimelineConfig{
			Direction: "vertical",
			Items:     timelineBottomOnlyItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Vertical timeline with left side only", `@daisyui.Timeline(daisyui.TimelineConfig{
	Direction: "vertical",
	Items:     timelineTopOnlyItems(),
})`, daisyui.Timeline(daisyui.TimelineConfig{
			Direction: "vertical",
			Items:     timelineTopOnlyItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Vertical timeline with different sides", `@daisyui.Timeline(daisyui.TimelineConfig{
	Direction: "vertical",
	Items:     timelineDifferentSidesItems(),
})`, daisyui.Timeline(daisyui.TimelineConfig{
			Direction: "vertical",
			Items:     timelineDifferentSidesItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Vertical timeline with colorful lines", `@daisyui.Timeline(daisyui.TimelineConfig{
	Direction: "vertical",
	Items:     timelineColorfulItems(),
})`, daisyui.Timeline(daisyui.TimelineConfig{
			Direction: "vertical",
			Items:     timelineColorfulItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Vertical timeline without icons", `@daisyui.Timeline(daisyui.TimelineConfig{
	Direction: "vertical",
	Items:     timelineNoIconsItems(),
})`, daisyui.Timeline(daisyui.TimelineConfig{
			Direction: "vertical",
			Items:     timelineNoIconsItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Responsive: vertical by default, horizontal on large screen", `@daisyui.Timeline(daisyui.TimelineConfig{
	Class: "timeline-vertical lg:timeline-horizontal",
	Items: timelineBothSidesItems(),
})`, daisyui.Timeline(daisyui.TimelineConfig{
			Class: "timeline-vertical lg:timeline-horizontal",
			Items: timelineBothSidesItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Timeline with icon snapped to the start", `@daisyui.Timeline(daisyui.TimelineConfig{
	Direction: "vertical",
	Modifier:  "snap-icon",
	Class:     "max-md:timeline-compact",
	Items:     timelineSnapItems(),
})

// timelineSnapItems uses rich Content via timelineSnapStartContent/timelineSnapEndContent:
{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineSnapStartContent("1984", "First Macintosh computer", "..."), HRAfter: true}
{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineSnapEndContent("1998", "iMac", "..."), HRBefore: true, HRAfter: true}
// ... alternating sides`, daisyui.Timeline(daisyui.TimelineConfig{
			Direction: "vertical",
			Modifier:  "snap-icon",
			Class:     "max-md:timeline-compact",
			Items:     timelineSnapItems(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func timelineBothSidesItems() []daisyui.TimelineItem {
	return []daisyui.TimelineItem{
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("1984"), Box: false, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("1998"), HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("2001"), HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("2007"), HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("2015"), HRBefore: true},
	}
}

func timelineBottomOnlyItems() []daisyui.TimelineItem {
	events := []string{"First Macintosh computer", "iMac", "iPod", "iPhone", "Apple Watch"}
	items := make([]daisyui.TimelineItem, len(events))
	for i, e := range events {
		item := daisyui.TimelineItem{
			Side:    daisyui.TimelineSideEnd,
			Icon:    timelineCheckIcon(),
			Content: timelineRaw(e),
			Box:     true,
		}
		if i > 0 {
			item.HRBefore = true
		}
		if i < len(events)-1 {
			item.HRAfter = true
		}
		items[i] = item
	}
	return items
}

func timelineTopOnlyItems() []daisyui.TimelineItem {
	events := []string{"First Macintosh computer", "iMac", "iPod", "iPhone", "Apple Watch"}
	items := make([]daisyui.TimelineItem, len(events))
	for i, e := range events {
		item := daisyui.TimelineItem{
			Side:    daisyui.TimelineSideStart,
			Icon:    timelineCheckIcon(),
			Content: timelineRaw(e),
			Box:     true,
		}
		if i > 0 {
			item.HRBefore = true
		}
		if i < len(events)-1 {
			item.HRAfter = true
		}
		items[i] = item
	}
	return items
}

func timelineDifferentSidesItems() []daisyui.TimelineItem {
	return []daisyui.TimelineItem{
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true},
		{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineRaw("iMac"), Box: true, HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("iPod"), Box: true, HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineRaw("iPhone"), Box: true, HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("Apple Watch"), Box: true, HRBefore: true},
	}
}

func timelineColorfulItems() []daisyui.TimelineItem {
	return []daisyui.TimelineItem{
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIconPrimary(), Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true, HRClass: "bg-primary"},
		{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIconPrimary(), Content: timelineRaw("iMac"), Box: true, HRBefore: true, HRAfter: true, HRClass: "bg-primary"},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIconPrimary(), Content: timelineRaw("iPod"), Box: true, HRBefore: true, HRAfter: true, HRClass: "bg-primary"},
		{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineRaw("iPhone"), Box: true, HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineRaw("Apple Watch"), Box: true, HRBefore: true},
	}
}

func timelineNoIconsItems() []daisyui.TimelineItem {
	return []daisyui.TimelineItem{
		{Side: daisyui.TimelineSideStart, Content: timelineRaw("First Macintosh computer"), Box: true, HRAfter: true},
		{Side: daisyui.TimelineSideEnd, Content: timelineRaw("iMac"), Box: true, HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Content: timelineRaw("iPod"), Box: true, HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideEnd, Content: timelineRaw("iPhone"), Box: true, HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Content: timelineRaw("Apple Watch"), Box: true, HRBefore: true},
	}
}

func timelineSnapItems() []daisyui.TimelineItem {
	return []daisyui.TimelineItem{
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineSnapStartContent("1984", "First Macintosh computer", "The Apple Macintosh—later rebranded as the Macintosh 128K—is the original Apple Macintosh personal computer. It played a pivotal role in establishing desktop publishing as a general office function."), HRAfter: true},
		{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineSnapEndContent("1998", "iMac", "iMac is a family of all-in-one Mac desktop computers designed and built by Apple Inc. It has been the primary part of Apple's consumer desktop offerings since its debut in August 1998, and has evolved through seven distinct forms."), HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineSnapStartContent("2001", "iPod", "The iPod is a discontinued series of portable media players and multi-purpose mobile devices designed and marketed by Apple Inc. The first version was released on October 23, 2001."), HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideEnd, Icon: timelineCheckIcon(), Content: timelineSnapEndContent("2007", "iPhone", "iPhone is a line of smartphones produced by Apple Inc. that use Apple's own iOS mobile operating system. The first-generation iPhone was announced by then-Apple CEO Steve Jobs on January 9, 2007."), HRBefore: true, HRAfter: true},
		{Side: daisyui.TimelineSideStart, Icon: timelineCheckIcon(), Content: timelineSnapStartContent("2015", "Apple Watch", "The Apple Watch is a line of smartwatches produced by Apple Inc. It incorporates fitness tracking, health-oriented capabilities, and wireless telecommunication, and integrates with iOS and other Apple products and services."), HRBefore: true},
	}
}

func timelineSnapStartContent(year, title, body string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"mb-10 md:text-end\"><time class=\"font-mono italic\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(year)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 241, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</time><div class=\"text-lg font-black\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 242, Col: 41}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(body)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 243, Col: 8}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func timelineSnapEndContent(year, title, body string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var10 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var10 == nil {
			templ_7745c5c3_Var10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"mb-10\"><time class=\"font-mono italic\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(year)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 249, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</time><div class=\"text-lg font-black\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 250, Col: 41}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 string
		templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(body)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/gallery/demos/demo_timeline.templ`, Line: 251, Col: 8}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func timelineRaw(s string) templ.Component {
	return templ.Raw(s)
}

func init() {
	registry.Register(registry.Entry{
		Slug:        "timeline",
		Name:        "Timeline",
		Description: "Timeline component shows a list of events in chronological order.",
		Category:    "daisyui",
		Body:        timelineBody,
	})
}

var _ = templruntime.GeneratedTemplate
