// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

func codeBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("mockup code with line prefix", `@daisyui.Code(daisyui.CodeConfig{
	Class: "w-full",
	Lines: []daisyui.CodeLine{
		{Prefix: "$", Text: "npm i daisyui"},
	},
})`, daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Prefix: "$", Text: "npm i daisyui"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Multi line", `@daisyui.Code(daisyui.CodeConfig{
	Class: "w-full",
	Lines: []daisyui.CodeLine{
		{Prefix: "$", Text: "npm i daisyui"},
		{Prefix: ">", Text: "installing...", Class: "text-warning"},
		{Prefix: ">", Text: "Done!", Class: "text-success"},
	},
})`, daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Prefix: "$", Text: "npm i daisyui"},
				{Prefix: ">", Text: "installing...", Class: "text-warning"},
				{Prefix: ">", Text: "Done!", Class: "text-success"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Highlighted line", `@daisyui.Code(daisyui.CodeConfig{
	Class: "w-full",
	Lines: []daisyui.CodeLine{
		{Prefix: "1", Text: "npm i daisyui"},
		{Prefix: "2", Text: "installing..."},
		{Prefix: "3", Text: "Error!", Class: "bg-warning text-warning-content"},
	},
})`, daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Prefix: "1", Text: "npm i daisyui"},
				{Prefix: "2", Text: "installing..."},
				{Prefix: "3", Text: "Error!", Class: "bg-warning text-warning-content"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Long line will scroll", `@daisyui.Code(daisyui.CodeConfig{
	Class: "w-full",
	Lines: []daisyui.CodeLine{
		{Prefix: "~", Text: "Magnam dolore beatae necessitatibus nemopsum itaque sit. Et porro quae qui et et dolore ratione."},
	},
})`, daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Prefix: "~", Text: "Magnam dolore beatae necessitatibus nemopsum itaque sit. Et porro quae qui et et dolore ratione."},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Without prefix", `@daisyui.Code(daisyui.CodeConfig{
	Class: "w-full",
	Lines: []daisyui.CodeLine{
		{Text: "without prefix"},
	},
})`, daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Text: "without prefix"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("With color", `@daisyui.Code(daisyui.CodeConfig{
	Class: "bg-primary text-primary-content w-full",
	Lines: []daisyui.CodeLine{
		{Text: "can be any color!"},
	},
})`, daisyui.Code(daisyui.CodeConfig{
			Class: "bg-primary text-primary-content w-full",
			Lines: []daisyui.CodeLine{
				{Text: "can be any color!"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func init() {
	registry.Register(registry.Entry{
		Slug:        "code",
		Name:        "Code mockup",
		Description: "Code mockup is used to show a block of code in a box that looks like a code editor.",
		Category:    "daisyui",
		Body:        codeBody,
	})
}

var _ = templruntime.GeneratedTemplate
