// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

func init() {
	registry.Register(registry.Entry{
		Slug:        "accordion",
		Name:        "Accordion",
		Description: "Accordion is used for showing and hiding content but only one item can stay open at a time.",
		Category:    "daisyui",
		Body:        accordionBody,
	})
}

func accordionBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Accordion using radio inputs", `@daisyui.Accordion(
	"my-accordion-1",
	[]daisyui.AccordionItem{
		{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button...", Open: true},
		{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\"..."},
		{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings..."},
	},
	"",
	false,
)`, daisyui.Accordion(
			"my-accordion-1",
			[]daisyui.AccordionItem{
				{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button in the top right corner and follow the registration process.", Open: true},
				{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\" on the login page and follow the instructions sent to your email."},
				{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings and select \"Edit Profile\" to make changes."},
			},
			"",
			false,
			false,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Accordion with arrow icon", `@daisyui.Accordion(
	"my-accordion-2",
	[]daisyui.AccordionItem{
		{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button...", Open: true},
		{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\"..."},
		{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings..."},
	},
	"arrow",
	false,
)`, daisyui.Accordion(
			"my-accordion-2",
			[]daisyui.AccordionItem{
				{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button in the top right corner and follow the registration process.", Open: true},
				{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\" on the login page and follow the instructions sent to your email."},
				{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings and select \"Edit Profile\" to make changes."},
			},
			"arrow",
			false,
			false,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Accordion with plus/minus icon", `@daisyui.Accordion(
	"my-accordion-3",
	[]daisyui.AccordionItem{
		{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button...", Open: true},
		{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\"..."},
		{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings..."},
	},
	"plus",
	false,
)`, daisyui.Accordion(
			"my-accordion-3",
			[]daisyui.AccordionItem{
				{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button in the top right corner and follow the registration process.", Open: true},
				{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\" on the login page and follow the instructions sent to your email."},
				{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings and select \"Edit Profile\" to make changes."},
			},
			"plus",
			false,
			false,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Accordion joined", `@daisyui.Accordion(
	"my-accordion-4",
	[]daisyui.AccordionItem{
		{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button...", Open: true},
		{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\"..."},
		{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings..."},
	},
	"arrow",
	true,
)`, daisyui.Accordion(
			"my-accordion-4",
			[]daisyui.AccordionItem{
				{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button in the top right corner and follow the registration process.", Open: true},
				{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\" on the login page and follow the instructions sent to your email."},
				{Title: "How do I update my profile information?", Content: "Go to \"My Account\" settings and select \"Edit Profile\" to make changes."},
			},
			"arrow",
			true,
			false,
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Accordion with glass", `@daisyui.Accordion(
	"my-accordion-5",
	[]daisyui.AccordionItem{
		{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button...", Open: true},
		{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\"..."},
	},
	"arrow",
	true,
		true,
	)`, gallery.GlassBackdrop(daisyui.Accordion(
			"my-accordion-5",
			[]daisyui.AccordionItem{
				{Title: "How do I create an account?", Content: "Click the \"Sign Up\" button in the top right corner and follow the registration process.", Open: true},
				{Title: "I forgot my password. What should I do?", Content: "Click on \"Forgot Password\" on the login page and follow the instructions sent to your email."},
			},
			"arrow",
			true,
			true,
		))).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
