// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package demos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/templ-ui/daisyui"
	"github.com/geoffjay/templ-ui/examples/gallery"
	"github.com/geoffjay/templ-ui/internal/registry"
)

func progressBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = gallery.Section("Progress", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "10", Max: "100", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "70", Max: "100", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Class: "w-56"})
</div>`, progressColorRow("")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Primary color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "primary", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "primary", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "primary", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("primary")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Secondary color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "secondary", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "secondary", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "secondary", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("secondary")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Accent color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "accent", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "accent", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "accent", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("accent")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Neutral color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "neutral", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "neutral", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "neutral", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("neutral")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Info color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "info", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "info", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "info", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("info")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Success color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "success", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "success", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "success", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("success")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Warning color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "warning", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "warning", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "warning", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("warning")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Error color", `<div class="flex flex-col gap-2 items-center">
	@daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: "error", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: "error", Class: "w-56"})
	@daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: "error", Class: "w-56"})
	// ... one per value
</div>`, progressColorRow("error")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = gallery.Section("Indeterminate (without value)", `@daisyui.Progress(daisyui.ProgressConfig{Class: "w-56"})`, daisyui.Progress(daisyui.ProgressConfig{Class: "w-56"})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func progressColorRow(color string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col gap-2 items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Progress(daisyui.ProgressConfig{Value: "0", Max: "100", Color: color, Class: "w-56"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Progress(daisyui.ProgressConfig{Value: "10", Max: "100", Color: color, Class: "w-56"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Progress(daisyui.ProgressConfig{Value: "40", Max: "100", Color: color, Class: "w-56"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Progress(daisyui.ProgressConfig{Value: "70", Max: "100", Color: color, Class: "w-56"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Progress(daisyui.ProgressConfig{Value: "100", Max: "100", Color: color, Class: "w-56"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func init() {
	registry.Register(registry.Entry{
		Slug:        "progress",
		Name:        "Progress",
		Description: "Progress bar can be used to show the progress of a task or to show the passing of time.",
		Category:    "daisyui",
		Body:        progressBody,
	})
}

var _ = templruntime.GeneratedTemplate
